name: Build and test imgcat
on: [push, pull_request]

jobs:
  test:
    name: Build and test imgcat
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
    steps:
      - name: Checkout imgcat
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: make
      - name: Test
        run: make test
